name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release_github:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1.16.0
        with:
          artifacts: "dist/*"
          generateReleaseNotes: true
